FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=builder /app/dist/local-bite-frontend/browser /usr/share/nginx/html
COPY public-nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
